import { initSchema } from './schema';
import db from './database';
import bcrypt from 'bcryptjs';

initSchema();

// ── Default admin user ──────────────────────────────────────────────────────
// Seeded on first run; safe to re-run (INSERT OR IGNORE + promotion pass).
const DEFAULT_ADMIN = {
  username: 'admin',
  email: 'admin@volleytrip.local',
  password: 'admin123',
};

const existingAdmin = db
  .prepare('SELECT id FROM users WHERE email = ?')
  .get(DEFAULT_ADMIN.email);

if (!existingAdmin) {
  const hash = bcrypt.hashSync(DEFAULT_ADMIN.password, 10);
  db.prepare(
    `INSERT INTO users (username, email, password_hash, is_admin, is_active)
     VALUES (?, ?, ?, 1, 1)`
  ).run(DEFAULT_ADMIN.username, DEFAULT_ADMIN.email, hash);
  console.log(
    `Seeded default admin: ${DEFAULT_ADMIN.email} / ${DEFAULT_ADMIN.password} — change this password after first login.`
  );
} else {
  // Ensure the default admin always retains admin rights + active status.
  db.prepare('UPDATE users SET is_admin = 1, is_active = 1 WHERE email = ?')
    .run(DEFAULT_ADMIN.email);
}

// Promote any emails listed in ADMIN_EMAILS (comma-separated) to admin.
const whitelist = (process.env.ADMIN_EMAILS ?? '')
  .split(',')
  .map(e => e.trim().toLowerCase())
  .filter(Boolean);
for (const email of whitelist) {
  db.prepare('UPDATE users SET is_admin = 1 WHERE lower(email) = ?').run(email);
}

const teams = [
  // ─── Italy: SuperLega ───────────────────────────────────────────────
  {
    name: 'Sir Susa Scai Perugia',
    short_name: 'Perugia',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Perugia',
    arena_name: 'PalaBarton',
    lat: 43.1073,
    lng: 12.3908,
    primary_color: '#000000',
    website_url: 'https://www.sirperugia.it',
  },
  {
    name: 'Itas Trentino',
    short_name: 'Trentino',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Trento',
    arena_name: 'Il T Quotidiano Arena',
    lat: 46.0830,
    lng: 11.1170,
    primary_color: '#FFD700',
    website_url: 'https://www.itatrentino.it',
  },
  {
    name: 'Allianz Milano',
    short_name: 'Milano',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Milan',
    arena_name: 'Allianz Cloud',
    lat: 45.4784,
    lng: 9.1236,
    primary_color: '#d32f2f',
    website_url: 'https://www.pallavolomilanossd.it',
  },
  {
    name: 'Cucine Lube Civitanova',
    short_name: 'Civitanova',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Civitanova Marche',
    arena_name: 'Eurosuole Forum',
    lat: 43.3036,
    lng: 13.7354,
    primary_color: '#1565c0',
    website_url: 'https://www.lubevolley.it',
  },
  {
    name: 'Valsa Group Modena',
    short_name: 'Modena',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Modena',
    arena_name: 'PalaPanini',
    lat: 44.6481,
    lng: 10.9502,
    primary_color: '#FFD700',
    website_url: 'https://www.volley.it',
  },
  {
    name: 'Cisterna Volley',
    short_name: 'Cisterna',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Cisterna di Latina',
    arena_name: 'Palazzetto dello Sport Cisterna',
    lat: 41.5918,
    lng: 12.8275,
    primary_color: '#e53935',
    website_url: 'https://www.cisternavolley.it',
  },
  {
    name: 'MA Acqua S.Bernardo Cuneo',
    short_name: 'Cuneo',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Cuneo',
    arena_name: 'Pala UBI Banca',
    lat: 44.3843,
    lng: 7.5426,
    primary_color: '#1565c0',
    website_url: 'https://www.pallavolocuneo.it',
  },
  {
    name: 'Rana Verona',
    short_name: 'Verona',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Verona',
    arena_name: 'AGSM Forum',
    lat: 45.4237,
    lng: 10.9867,
    primary_color: '#FFD700',
    website_url: 'https://www.volleyverona.it',
  },
  {
    name: 'Sonepar Padova',
    short_name: 'Padova',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Padova',
    arena_name: 'Kioene Arena',
    lat: 45.3964,
    lng: 11.8787,
    primary_color: '#e65100',
    website_url: 'https://www.pallavolopadova.com',
  },
  {
    name: 'Mint Vero Volley Monza',
    short_name: 'Monza',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Monza',
    arena_name: 'Opiquad Arena',
    lat: 45.5845,
    lng: 9.2744,
    primary_color: '#c62828',
    website_url: 'https://www.verovolleys.it',
  },
  {
    name: 'Yuasa Battery Grottazzolina',
    short_name: 'Grottazzolina',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Grottazzolina',
    arena_name: 'Tenax Arena',
    lat: 43.3167,
    lng: 13.6167,
    primary_color: '#1b5e20',
    website_url: 'https://www.volleygrottazzolina.it',
  },
  {
    name: 'Gas Sales Bluenergy Piacenza',
    short_name: 'Piacenza',
    league: 'SuperLega',
    country: 'Italy',
    city: 'Piacenza',
    arena_name: 'PalaBanca',
    lat: 45.0502,
    lng: 9.7077,
    primary_color: '#e53935',
    website_url: 'https://www.pallavolopiacenza.it',
  },

  // ─── Japan: SV.League Men (2024–25) ────────────────────────────────
  {
    name: 'VOREAS HOKKAIDO',
    short_name: 'Voreas',
    league: 'SV.League',
    country: 'Japan',
    city: 'Kitahiroshima',
    arena_name: 'Hokkaido Ballpark F Village Arena',
    lat: 43.0172,
    lng: 141.5628,
    primary_color: '#1565c0',
    website_url: 'https://voreas.co.jp',
  },
  {
    name: 'Tokyo Great Bears',
    short_name: 'Great Bears',
    league: 'SV.League',
    country: 'Japan',
    city: 'Tokyo',
    arena_name: 'Komazawa Olympic Park Gymnasium',
    lat: 35.6437,
    lng: 139.6697,
    primary_color: '#c62828',
    website_url: 'https://tokyogreatbears.com',
  },
  {
    name: 'VC NAGANO TRIDENTS',
    short_name: 'Tridents',
    league: 'SV.League',
    country: 'Japan',
    city: 'Nagano',
    arena_name: 'Nagano City Gymnasium',
    lat: 36.6486,
    lng: 138.1947,
    primary_color: '#00838f',
    website_url: 'https://vcnagano.com',
  },
  {
    name: 'TORAY ARROWS SHIZUOKA',
    short_name: 'Toray Arrows',
    league: 'SV.League',
    country: 'Japan',
    city: 'Mishima',
    arena_name: 'Mishima Fieldwork Arena',
    lat: 35.1218,
    lng: 138.9104,
    primary_color: '#1b5e20',
    website_url: 'https://www.toray.co.jp/sports/arrows',
  },
  {
    name: 'JTEKT STINGS AICHI',
    short_name: 'JTEKT',
    league: 'SV.League',
    country: 'Japan',
    city: 'Kariya',
    arena_name: 'Aisin Wellth Arena Kariya',
    lat: 34.9897,
    lng: 137.0014,
    primary_color: '#0d47a1',
    website_url: 'https://jtekt-stings.com',
  },
  {
    name: 'WOLFDOGS NAGOYA',
    short_name: 'Wolfdogs',
    league: 'SV.League',
    country: 'Japan',
    city: 'Nagoya',
    arena_name: 'Dolphins Arena',
    lat: 35.1709,
    lng: 136.8815,
    primary_color: '#37474f',
    website_url: 'https://wolfdogs.denso.com',
  },
  {
    name: 'OSAKA BLUTEON',
    short_name: 'Bluteon',
    league: 'SV.League',
    country: 'Japan',
    city: 'Osaka',
    arena_name: 'Panasonic Arena',
    lat: 34.7010,
    lng: 135.4960,
    primary_color: '#1565c0',
    website_url: 'https://osakavolleyball.com',
  },
  {
    name: 'SUNTORY SUNBIRDS OSAKA',
    short_name: 'Sunbirds',
    league: 'SV.League',
    country: 'Japan',
    city: 'Osaka',
    arena_name: 'Osaka Prefectural Gymnasium',
    lat: 34.6618,
    lng: 135.5022,
    primary_color: '#0277bd',
    website_url: 'https://www.sunbirds.jp',
  },
  {
    name: 'NIPPON STEEL SAKAI BLAZERS',
    short_name: 'Blazers',
    league: 'SV.League',
    country: 'Japan',
    city: 'Sakai',
    arena_name: 'J-GREEN Sakai',
    lat: 34.5418,
    lng: 135.4953,
    primary_color: '#b71c1c',
    website_url: 'https://ns-blazers.com',
  },
  {
    name: 'HIROSHIMA THUNDERS',
    short_name: 'Thunders',
    league: 'SV.League',
    country: 'Japan',
    city: 'Hiroshima',
    arena_name: 'Hiroshima Green Arena',
    lat: 34.3853,
    lng: 132.4553,
    primary_color: '#e53935',
    website_url: 'https://hiroshima-thunders.com',
  },

  // ─── Poland: PlusLiga 2025-26 ───────────────────────────────────────
  {
    name: 'Jastrzębski Węgiel',
    short_name: 'Jastrzębski',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Jastrzębie-Zdrój',
    arena_name: 'Hala Widowiskowo-Sportowa',
    lat: 49.9575,
    lng: 18.5982,
    primary_color: '#1b5e20',
    website_url: 'https://jastrzebski.pl',
  },
  {
    name: 'ZAKSA Kędzierzyn-Koźle',
    short_name: 'ZAKSA',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Kędzierzyn-Koźle',
    arena_name: 'Azoty Arena',
    lat: 50.3413,
    lng: 18.2325,
    primary_color: '#e65100',
    website_url: 'https://zaksa.pl',
  },
  {
    name: 'PGE Projekt Warszawa',
    short_name: 'Projekt',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Warsaw',
    arena_name: 'Torwar Arena',
    lat: 52.2186,
    lng: 21.0262,
    primary_color: '#880e4f',
    website_url: 'https://projektwarsawa.pl',
  },
  {
    name: 'Asseco Resovia',
    short_name: 'Resovia',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Rzeszów',
    arena_name: 'Podpromie Sports Hall',
    lat: 50.0412,
    lng: 22.0064,
    primary_color: '#b71c1c',
    website_url: 'https://resovia.pl',
  },
  {
    name: 'Aluron CMC Warta Zawiercie',
    short_name: 'Zawiercie',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Zawiercie',
    arena_name: 'Hala Widowiskowo-Sportowa Zawiercie',
    lat: 50.4858,
    lng: 19.4238,
    primary_color: '#0277bd',
    website_url: 'https://wartazawiercie.pl',
  },
  {
    name: 'Indykpol AZS Olsztyn',
    short_name: 'AZS Olsztyn',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Olsztyn',
    arena_name: 'Urania Sports Hall',
    lat: 53.7799,
    lng: 20.4801,
    primary_color: '#33691e',
    website_url: 'https://azsolsztyn.pl',
  },
  {
    name: 'PGE GiEK Skra Bełchatów',
    short_name: 'Skra',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Bełchatów',
    arena_name: 'Hala Energia Bełchatów',
    lat: 51.3606,
    lng: 19.3570,
    primary_color: '#f57f17',
    website_url: 'https://skra.pl',
  },
  {
    name: 'Energa Trefl Gdańsk',
    short_name: 'Trefl Gdańsk',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Gdańsk',
    arena_name: 'Ergo Arena',
    lat: 54.3979,
    lng: 18.5880,
    primary_color: '#0d47a1',
    website_url: 'https://trefls.pl',
  },
  {
    name: 'Bogdanka LUK Lublin',
    short_name: 'LUK Lublin',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Lublin',
    arena_name: 'Hala Globus',
    lat: 51.2465,
    lng: 22.5684,
    primary_color: '#4a148c',
    website_url: 'https://luklublin.pl',
  },
  {
    name: 'Ślepsk Malow Suwałki',
    short_name: 'Suwałki',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Suwałki',
    arena_name: 'Hala Sportowo-Widowiskowa Suwałki',
    lat: 54.1115,
    lng: 22.9303,
    primary_color: '#1565c0',
    website_url: 'https://slepsk.pl',
  },
  {
    name: 'Cuprum Stilon Gorzów',
    short_name: 'Gorzów',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Gorzów Wielkopolski',
    arena_name: 'CRS Gorzów',
    lat: 52.7369,
    lng: 15.2288,
    primary_color: '#bf360c',
    website_url: 'https://cuprum.gorzow.pl',
  },
  {
    name: 'Inpost ChKS Chełm',
    short_name: 'Chełm',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Chełm',
    arena_name: 'Hala Sportowa MOSIR Chełm',
    lat: 51.1432,
    lng: 23.4716,
    primary_color: '#e53935',
    website_url: 'https://chkschelm.pl',
  },
  {
    name: 'Norwid Częstochowa',
    short_name: 'Częstochowa',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Częstochowa',
    arena_name: 'Hala Sportowa Częstochowa',
    lat: 50.8118,
    lng: 19.1203,
    primary_color: '#880e4f',
    website_url: 'https://norwid.pl',
  },
  {
    name: 'Barkom-Kazhany Lviv',
    short_name: 'Barkom Lviv',
    league: 'PlusLiga',
    country: 'Poland',
    city: 'Lviv',
    arena_name: 'Sportpalace SKA Lviv',
    lat: 49.8397,
    lng: 24.0297,
    primary_color: '#1a237e',
    website_url: 'https://barkom.ua',
  },

  // ─── Turkey: Efeler Ligi 2025-26 ────────────────────────────────────
  {
    name: 'Ziraat Bankası S.K.',
    short_name: 'Ziraat',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Ankara',
    arena_name: 'Ankara Spor Salonu',
    lat: 39.9418,
    lng: 32.8647,
    primary_color: '#004d40',
    website_url: 'https://ziraatbankasispor.com',
  },
  {
    name: 'Halkbank S.K.',
    short_name: 'Halkbank',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Ankara',
    arena_name: 'Spor Toto Spor Salonu',
    lat: 39.9334,
    lng: 32.8597,
    primary_color: '#1b5e20',
    website_url: 'https://halkbankspor.com',
  },
  {
    name: 'Galatasaray HDI Sigorta',
    short_name: 'Galatasaray',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'İstanbul',
    arena_name: 'Galatasaray Spor Salonu',
    lat: 41.0082,
    lng: 28.9784,
    primary_color: '#e53935',
    website_url: 'https://galatasaray.org',
  },
  {
    name: 'Spor Toto S.K.',
    short_name: 'Spor Toto',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Ankara',
    arena_name: 'Ankara Spor Toto Spor Kompleksi',
    lat: 39.9256,
    lng: 32.8560,
    primary_color: '#c62828',
    website_url: 'https://sportorosk.com',
  },
  {
    name: 'İstanbul GSK',
    short_name: 'İstanbul GSK',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'İstanbul',
    arena_name: 'İstanbul GSK Spor Salonu',
    lat: 41.0082,
    lng: 28.9710,
    primary_color: '#0277bd',
    website_url: 'https://istanbulgsk.com',
  },
  {
    name: 'Fenerbahçe HDI Sigorta',
    short_name: 'Fenerbahçe',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'İstanbul',
    arena_name: 'Burhan Felek Voleybol Salonu',
    lat: 40.9776,
    lng: 29.0327,
    primary_color: '#FFD700',
    website_url: 'https://fbvoleybol.com',
  },
  {
    name: 'Bursa Büyükşehir Belediyespor',
    short_name: 'Bursa',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Bursa',
    arena_name: 'Bursa Osmangazi Spor Salonu',
    lat: 40.1828,
    lng: 29.0664,
    primary_color: '#6a1b9a',
    website_url: 'https://bbsk.com.tr',
  },
  {
    name: 'Altekma S.K.',
    short_name: 'Altekma',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Hatay',
    arena_name: 'Hatay Spor Salonu',
    lat: 36.2023,
    lng: 36.1613,
    primary_color: '#37474f',
    website_url: 'https://altekma.com',
  },
  {
    name: 'Gebze Belediyespor',
    short_name: 'Gebze',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Gebze',
    arena_name: 'Gebze Belediyesi Spor Salonu',
    lat: 40.8029,
    lng: 29.4305,
    primary_color: '#1565c0',
    website_url: 'https://gebzebelediye.com.tr',
  },
  {
    name: 'Gaziantep Gençlik Spor',
    short_name: 'Gaziantep',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Gaziantep',
    arena_name: 'Gaziantep Spor Salonu',
    lat: 37.0662,
    lng: 37.3833,
    primary_color: '#e65100',
    website_url: 'https://genclikspor.org',
  },
  {
    name: 'İstanbul Büyükşehir Belediyespor',
    short_name: 'İstanbul BB',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'İstanbul',
    arena_name: 'Atatürk Olimpiyat Stadı Spor Salonu',
    lat: 41.0766,
    lng: 28.7654,
    primary_color: '#0d47a1',
    website_url: 'https://ibbspor.com',
  },
  {
    name: 'Alanya Belediyespor',
    short_name: 'Alanya Bld',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Alanya',
    arena_name: 'Alanya Belediyesi Spor Salonu',
    lat: 36.5442,
    lng: 32.0060,
    primary_color: '#f57f17',
    website_url: 'https://alanyabelediyespor.com',
  },
  {
    name: 'Akkuş Belediyespor',
    short_name: 'Akkuş Bld',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Akkuş',
    arena_name: 'Akkuş Belediyesi Spor Salonu',
    lat: 40.7986,
    lng: 36.9706,
    primary_color: '#2e7d32',
    website_url: 'https://akkusbelediye.com',
  },
  {
    name: 'Cizre Belediyespor',
    short_name: 'Cizre Bld',
    league: 'Efeler Ligi',
    country: 'Turkey',
    city: 'Cizre',
    arena_name: 'Cizre Belediyesi Spor Salonu',
    lat: 37.3260,
    lng: 42.1908,
    primary_color: '#880e4f',
    website_url: 'https://cizrebelediye.net',
  },
];

const insertTeam = db.prepare(`
  INSERT OR IGNORE INTO teams
    (name, short_name, league, country, city, arena_name, lat, lng, primary_color, website_url)
  VALUES
    (@name, @short_name, @league, @country, @city, @arena_name, @lat, @lng, @primary_color, @website_url)
`);

db.exec('BEGIN');
try {
  for (const team of teams) {
    insertTeam.run(team as any);
  }
  db.exec('COMMIT');
} catch (err) {
  db.exec('ROLLBACK');
  throw err;
}

console.log(`Seeded ${teams.length} teams successfully.`);
